### ISSUE TITLE
Navbar links on pages other than home page are not linked.

### ISSUE THREAD

**Issue by grvashu** [grvashu/srishti-live-17#12]
Need to add links on navbar items.

**Comment by grvashu** [comment]
Do not copy the entire navbar div from home page.
Copy all the individual links (href) in one page's navbar and then copy that nav div to all other pages.

**Comment by sapnanayak** [comment]
Having a small problem with this. The links are relative to the page since they are all within single page. Hence although href is same even on project page navbar, it says page not found

**Comment by grvashu** [comment]
You will have to write them as
`href="../index.html#id"`

**Comment by sapnanayak** [comment]
Done from my side for project pages
