### ISSUE TITLE
add game of life on all pages

### ISSUE THREAD

**Issue by NitishChopra09** [grvashu/srishti-live-17#129]

**Comment by NitishChopra09** [comment]
Can you do this, since we've never really interfered on  this before?

**Comment by sapnanayak** [comment]
I started trying to do this.. but this is causing some issue with the header.. I dont know why..can you check and then I will do the updation
![screenshot 119](https://user-images.githubusercontent.com/30742625/33923615-29bab220-dff8-11e7-8c75-b02e1983a88a.png)

**Comment by grvashu** [comment]
Ok, this change isn't merged yet. Right?

**Comment by grvashu** [comment]
@sapnanayak fixed game of life css. The issue won't occur now.
 You can now copy the game of life files to all the pages.
