### ISSUE TITLE
old favicon diff on project page, artist page and contact us page.

### ISSUE THREAD

**Issue by NitishChopra09** [grvashu/srishti-live-17#132]

**Comment by NitishChopra09** [comment]
only on the homepage the favicon is the the srishti logo, rest everywhere it's the srishti live logo.

**Comment by grvashu** [comment]
I was just trying srishti logo as favicon on the home page.
What do you guys think we should keep as favicon logo? @NitishChopra09 @meerasanghani @sapnanayak

**Comment by meerasanghani** [comment]
srishti logo works for me
srishti live isnot recognisable

**Comment by grvashu** [comment]
@meerasanghani cool. let's change to srishti logo.
Confirm this with Nitish and Sapna and please change the favicon across all pages.

Favicon is only changed on the home page right now. Needs to be updated across website.

Favicon file: assets/images/favicon.png
