### ISSUE TITLE
schedule page rendering

### ISSUE THREAD

**Issue by grvashu** [grvashu/srishti-live-17#136]
- resolved broken link. the file was missing.
- header/nav doesn't stick
- section padding/margin is not consistent.

**Comment by NitishChopra09** [comment]
the change i just pushed for the schedule pages should ideally sort this issue. Please do check.

**Comment by NitishChopra09** [comment]
the header issue it's still not solved. sapna and I is looking into it.

**Comment by grvashu** [comment]
resolved
