### ISSUE TITLE
Font rendering

### ISSUE THREAD

**Issue by grvashu** [grvashu/srishti-live-17#15]
Can anyone confirm if fonts (Archer and Rasa) are rendering properly now? I have fixed and they seem to work on my local machine.

[grvashu.github.io/srishti-live-17/](url)

If possible, please attach a screenshot of the home page.

**Comment by sapnanayak** [comment]
![screenshot 116](https://user-images.githubusercontent.com/30742625/33671819-a9d93e9c-dace-11e7-9fe0-15568fed8c61.png)
Looks like only rasa is updated to me
