### ISSUE TITLE
Link logo in navigation to index

### ISSUE THREAD

**Issue by grvashu** [grvashu/srishti-live-17#26]
Add logo href to point index (homepage).

**Comment by grvashu** [comment]
Check if the logo in header links back to home page throughout website.

**Comment by NitishChopra09** [comment]
@grvashu  since the header is an included html code - if its functional on one page shouldn't it be functional on all pages?

**Comment by grvashu** [comment]
@NitishChopra09 This is an outdated issue. Close this issue if it works across already.
